# Generated by Django 5.0.6 on 2024-06-28 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('ClassId', models.AutoField(primary_key=True, serialize=False)),
                ('ClassName', models.CharField(max_length=100)),
                ('Course', models.ManyToManyField(to='EducationSystem.course')),
            ],
            options={
                'db_table': 'Class',
            },
        ),
        migrations.CreateModel(
            name='CustUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('User', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CustUser',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EducationSystem.custuser')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('MarksId', models.AutoField(primary_key=True, serialize=False)),
                ('Marks', models.PositiveIntegerField()),
                ('Class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EducationSystem.class')),
                ('Course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EducationSystem.course')),
                ('Student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EducationSystem.student')),
            ],
            options={
                'db_table': 'Mark',
            },
        ),
        migrations.AddField(
            model_name='class',
            name='Student',
            field=models.ManyToManyField(to='EducationSystem.student'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherId', models.AutoField(primary_key=True, serialize=False)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EducationSystem.custuser')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='Teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EducationSystem.teacher'),
        ),
    ]
